name: MacOS Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    name: Build on macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build
        run: zig build
